services:
  fekra-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:80"
      - "4450:443"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fekra-backend
    networks:
      - fekra-network

  fekra-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5035:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - PORT=5000
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET} 
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - PAYMENT_SS_RETENTION_DAYS=30
    networks:
      - fekra-network
    volumes:
      - fekra-uploads:/app/uploads

networks:
  fekra-network:
    driver: bridge

volumes:
  fekra-uploads:
